version: '3.2'
services:
    auth:
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: auth
    orders:
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: orders
    catalog:
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: catalog
    basket:
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: basket
    mysql.data:
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: mysql.data
    redis.data:
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: redis.data
    web.spa:
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: web.spa